### ISSUE TITLE
strava.github.io/iD not connecting to api

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [paulmach/slide#10]

**Comment by EwenH** [comment]
Are you using http or https for the URL? 

The http does not allow you to save as OpenStreetMap has been updated only to use secure connections. It would be useful if http is deployed, then it reverts to https or at least warns you.

Try
https://strava.github.io/iD/#background=Bing&map=18.00/147.00335/-36.77650

**Comment by erickdeoliveiraleal** [comment]
Thank you
