### ISSUE TITLE
Unable to Save Edits, Possible OAuth Problem

### ISSUE THREAD

**Issue by pdxvr** [paulmach/slide#11]
I've tried a number of browsers but I cannot save edits anymore.  The OSM OAuth popup window comes up asking me to grant access repeatedly but won't go past that.  If I restart my session, the popup window comes up, but there is no content in it.  The url for it is about: blank.

**Comment by paulmach** [comment]
are you using https?  OSM recently started requiring it and the strava ID version is way out of date so it doesn't use it automatically.

see https://github.com/paulmach/slide/issues/10#issuecomment-364096642

**Comment by pdxvr** [comment]
That resolves it, thanks.  So simple.
