### ISSUE TITLE
Unable to connect to API

### ISSUE THREAD

**Issue by cristian5th** [paulmach/slide#8]
Hello.

This is probably my computer's issue instead of a project's issue but this is the only way I found to contact Paul.

Since the beginning of the year, I cannot save my changes anymore. Somebody is unable to connect to API. I don’t know if Strava, the iD editor, Open Street Maps or Github.

If I clear all my caches and local data and remove all authorizations I may have given, then I can go to the iD editor with Slide add-on and everything will be there: the Strava heatmap, the Open Street Maps roads and paths, the local GPX file I may upload,… I can make the changes as usual. Then I clic on the save button and Open Street Map request my authorization which I gladly give, but that’s the end of it. The changes will remain local and I will be shown a message saying “Unable to connect to API.”

If I do not clear my caches and local data, then, when I go the iD editor with Slide add-on, I will only see the Bing background with the Strava heatmap but no Open Street Maps features and still the "Unable to connect to API” message.

![screen shot 2018-01-14 at 19 19 40](https://user-images.githubusercontent.com/35431417/34919410-dcdee86a-f963-11e7-9d22-5fe27424443e.png)

Is there anything I can change in my computer to fix the issue and be able to edit the maps as I have been doing for years?

Thanks a lot for your help. Best regards.

**Comment by paulmach** [comment]
The slide iD is on a very very old version so that's probably related to the problem.

I just tested and if you visit the HTTPS version of the page things work, but HTTP it doesn't. I think this is related to OSM's recent transition to HTTPS only.

Do you still have the problem if you visit https://strava.github.io and try to login+edit+save?

**Comment by cristian5th** [comment]
Yes, that is exactly the problem.

I was opening the webpage http://strava.github.io where I could not get the OSM data, but when I open now https://strava.github.io, then everything works as before.

Many, many thanks for your help and for this application bringing the heatmap and the slide feature to OSM. It saves me a lot of time.

Warmest regards.
